#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2020 Jaromil <jaromil@dyne.org>
# SPDX-FileCopyrightText: 2020 Puria Nafisi Azizi <puria@dyne.org>
#
# SPDX-License-Identifier: Unlicense

# This is free and unencumbered software released into the public domain.

# This script lists all categories by extension in JSON format.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -eu

script_dir=$(dirname "$(readlink -f "$0")")
proj_dir="$(cd "$script_dir"/..; pwd)"
build_dir="$proj_dir/build"
data_dir="$proj_dir/data/categories"

cd "$data_dir"

grep -r "" ./*.csv \
	| sed -e 's|^\./||' -e 's/\.csv//' -e 's/,.*$//' \
	| sort -t : -k 2 \
	| awk -F : -e '
		BEGIN {
			prev_ext=""
			first_ext=1
			printf "{\n"
		}
		{
			ext=$2
			cat=$1
			if (ext == prev_ext) {
				printf ", \"%s\"", cat
			} else {
				if (!first_ext) {
					printf "],\n"
				}
				printf "\t\"%s\": [\"%s\"", ext, cat
				prev_ext=ext
			}
			first_ext=0
		}
		END {
			printf "]\n}\n"
		}
	'

cd "$proj_dir"
