#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2020 Jaromil <jaromil@dyne.org>
# SPDX-FileCopyrightText: 2020 Puria Nafisi Azizi <puria@dyne.org>
#
# SPDX-License-Identifier: Unlicense

# This is free and unencumbered software released into the public domain.

# This script lists all duplicate extensions,
# and the categories they are contained in.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -eu

script_dir=$(dirname "$(readlink -f "$0")")

# cd to the project root
cd "$script_dir/.."

cd data

printf "%s\t%s\t%s\n" "ext" "prim" "others"
printf "%s\t%s\t%s\n" "---" "----" "------"

grep -r ",%" ./*.csv \
	| sed -e 's/^.*://' -e 's/,.*$//' \
	| while read -r ext
do
	cat_prime="$(grep -r "^$ext," | grep -v '%' | sed -e 's/\..*$//')"
	cat_other="$(grep -r "^$ext," | grep    '%' | sed -e 's/\..*$//' | tr '\n' ',' | sed -e 's/,.*$//')"
	printf  "%s\t%s\t%s\n" "$ext" "$cat_prime" "$cat_other"
done

