#!/usr/bin/env lua

-- This is free and unencumbered software released into the public domain.

-- This lua script lists all extensions by category
-- requires lfs extension (found in luarocks)
require'lfs'

hits={}
dupes={}
for file in lfs.dir[[data]] do
   if not (file == "." or file == "..") then
	  local fd = io.open('data/'..file, 'r')
	  for ext in fd:lines() do
		 if ext ~= '' then
			local e = string.match(ext,"(%w+)") -- eliminate %
			if hits[e] then -- dup
			   dupes[e] = hits[e] .. ' + ' .. file
			end
			hits[e] = file
		 end
	  end
   end
end

print("EXT\t\t duplicates")
print("---------------------------")
for k,v in pairs(dupes) do
   print(k.."\t\t "..v)
end

