#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2020 Jaromil <jaromil@dyne.org>
# SPDX-FileCopyrightText: 2020 Puria Nafisi Azizi <puria@dyne.org>
#
# SPDX-License-Identifier: Unlicense

# This is free and unencumbered software released into the public domain.

# This script lists all extensions by category.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -eu

script_dir=$(dirname "$(readlink -f "$0")")
proj_dir="$(cd "$script_dir"/..; pwd)"
build_dir="$proj_dir/build"
data_dir="$proj_dir/data"

cd "$data_dir"

for file in ./*.csv
do
	printf "%s:" "$(basename --suffix=".csv" "$file")"
	awk -F , -e '{ printf(" %s", $1); }' "$file"
	printf "\n"
done
