#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -eu

script_dir=$(dirname "$(readlink -f "$0")")
proj_dir="$(cd "$script_dir"/..; pwd)"
build_dir="$proj_dir/build"
data_dir="$proj_dir/data"

version() {
	git describe \
		--tags \
		--dirty \
		--broken \
		--always \
		--long \
		--candidates=99 \
		--first-parent
}

print_help() {

	echo "Run all we want to be done in our CI."
	echo
	echo "Usage:"
	echo "         $(basename "$0") [OPTIONS]"
	echo "Options:"
	echo "          -h, --help                  Show this help message"=
	echo "          -s, --install-requirements  Install whatever this script needs to run (works only on Debian/Ubuntu)"
}

# read command-line args
POSITIONAL=""
while [ "$#" -gt 0 ]
do
	arg="$1"
	shift # past argument

	case "$arg" in
		-h|--help)
			print_help
			exit 0
			;;
		*) # non-/unknown option
			POSITIONAL="$POSITIONAL $arg"
			;;
	esac
done
set -- "${POSITIONAL}" # restore positional parameters

cd "$proj_dir"

echo
echo "Delete old CI files ..."
rm -Rf "$build_dir"

echo
echo "Generate everything ..."
"$script_dir/build"

echo
echo "Evaluate project meta-data ..."
version="$(version)"
server_url="${GITHUB_SERVER_URL:-"https://github.com"}"
proj_dir_name="$(basename "$proj_dir")"
proj_slug="${GITHUB_REPOSITORY:-"$USER/$proj_dir_name"}"
proj_name="$(echo "$proj_slug" | sed -e 's|^.*/||')"
proj_url="$server_url/$proj_slug"
echo "version: $version"
echo "name:    $proj_name"
echo "slug:    $proj_slug"
echo "URL:     $proj_url"

echo
echo "Generate package/artifact ..."
package="${proj_name}_all-data_$version"
package_dir="$proj_dir/$package"
package_file="$build_dir/${package}.zip"
cd "$proj_dir"
mkdir -p "$package_dir"
cp -r "$build_dir/"* "$package_dir/"
cp -r "$data_dir/"* "$package_dir/"
zip -r "$package_file" "$package_dir"
rm -Rf "$package_dir"

echo
echo "Creating HTML ('index.html') that links to all the files generated above ..."
{
	cd "$build_dir"

	echo "<html>"
	echo "<head>"
	echo "<title>GitHub project $proj_slug - Generated files</title>"
	echo "</head>"
	echo "<body>"
	echo "<h1>GitHub project <a href=\"$proj_url/\">$proj_slug</a> - Generated files</h1>"
	echo "Version: <a href=\"$proj_url/tree/$version/\">$version</a><br>"
	echo "Files:<br>"
	echo "<ul>"
	find . -type f | sed -e 's|^\./||' | sort -t . -k 2 | while read -r file
	do
		printf '<li><a href="%s">%s</a></li>\n' "$file" "$file"
	done
	echo "</ul>"
	echo "<body>"
	echo "<html>"
} > "$proj_dir/index.html"
mv "$proj_dir/index.html" "$build_dir/index.html"

cd "$proj_dir"
echo
echo "done."
