# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

name: Generate parser, Render in other formats and host that

on: [push]

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Generate everything
      run: scripts/ci-run

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
